# Yaml / Mysql
Store: Yaml
Mysql:
  address: localhost
  port: 3306
  database: test
  user: root
  password: 123456
HikariCP:
  connectionTimeout: 30000
  #连接超时时间 默认值：30000（30秒）
  minimumIdle: 10
  #最小空闲连接数
  maximumPoolSize: 50
  #池允许达到的最大大小，包括空闲和正在使用的连接
settings:
  #玩家数据自动保存 s为单位
  auto-save: 600
  #随机池工作设定
  random:
    #随机池每次随机时随机总轮数
    #每次刷新商店时：
    #第一轮： 假设有5个商品位置
    #第一个商品：随机到了普通品质
    #第二个商品：随机到了普通品质
    #第三个商品：随机到了稀有品质
    #第四个商品：每个品质都没随机到
    #第五个商品：每个品质都没随机到
    #若第一轮有没被随机到的则进行下一轮
    #第二轮： 现在第四、五商品没被随机到
    #第四个商品：随机到史诗品质
    #第五个商品：仍未被随机到
    #第二轮还有商品未被随机到，则进行下一轮
    #....
    #直到不超过下面设定值的轮数中的某轮第五个商品被随机到商品后结束
    #或者到了设定值的轮数仍未有商品则该商品为空
    times: 20
message:
  plugin: '&7[&3&lLegendary&b&lDailyShop&7] '
  command_player:
    - '&3&lLegendary&b&lDailyShop &f—— &e指令帮助'
    - '&f &7> &a/lshop open 商店 &f打开指定商店'
  command_op:
    - '&3&lLegendary&b&lDailyShop &f—— &e管理员指令帮助'
    - '&f &7> &a/lshop add 商店 品级ID 最低价格 最高价格 限购数量(-1为无限) 货币类型(vault/playerpoints) 类型(buy/sell) &f将手上物品加入到该商店指定品质的随机池内'
    - '&f &7> &a/lshop random 玩家 商店ID &f立刻随机玩家指定商店'
    - '&f &7> &a/lshop points 玩家 商店ID 数量 &f给与玩家指定商店随机点数'
    - '&f &7> &a/lshop delete 商店 品级ID &f打开该商店的指定品质移除商品GUI'
    - '&f &7> &a/lshop reload &f重载配置文件'
  nopermission: '&c你没有该权限.'
  noshop: '&c该商店不存在！'
  noplayer: '&c该玩家不存在！'
  notonline: '&c该玩家不在你当前的区服或者不在线！'
  norarity: '&c该品质ID不存在！'
  norarityInShop: '&c该商店配置内没有添加该品质ID，请打开 &eShop/%shop% &c在其 &erarities &c下添加该品质ID'
  notnumber: '&c请输入一个正确的数字！'
  itemnull: '&c请手持一个需要上架的物品！'
  add: '&a成功添加 &f%item% &a到商店 &f%shop% &a的 %rarity% &a随机池内.'
  delete: '&c成功将 &f%item% &c从商店 &f%shop% &a的 %rarity% &c奖池中删去'
  unknown_currency: '&c未知的货币类型.请输入 &evault / playerpoints'
  unknown_type: '&c未知的商品类型.请输入 &ebuy（购买） / sell（收购）'
  max: '&c该商品已经不能再购买或者出售了！'
  vault_notenough: '&c你的游戏币不足 &e%price%'
  playerpoints_notenough: '&c你的点券不足 &e%price%'
  item_notenough: '&c你缺少物品 &f%item% &7×%amount%'
  vault_buy: '&e你花费了 &a%price% &e游戏币购买了 &f%item% &7×%amount%'
  playerpoints_buy: '&e你花费了 &a%price% &e点券购买了 &f%item% &7×%amount%'
  item_sell_vault: '&e你出售了 &f%item% &7×%amount% &e获得了 &a%price% &e游戏币'
  item_sell_playerpoints: '&e你出售了 &f%item% &7×%amount% &e获得了 &a%price% &e点券'
  random: '&e成功随机该商店，目前该商店还剩余 &a%amount% &e次随机点'
  random_cant: '&c该商店缺少随机点数！'
  random_admin: '&e你将玩家&f %player% &e的 &a%shop% &e商品刷新了'
  points_give: '&e你给与玩家 &f%player% &a%amount%点 &f%shop% &e的随机点数'
  points_recive: '&a你获得了 &e%amount%点 %shop% &a的随机点数'