name: LegendaryDailyShop
main: com.legendaryrealms.shop.LegendaryDailyShop
version: 2.0.5
softdepend:
  - PlaceholderAPI
depend:
  - Vault
  - PlayerPoints
commands:
  LegendaryDailyShop:
    aliases:
      - lshop
      - shop
      - lds